version: '3.8'

services:

  bot_service:
    build: .
    volumes:
      - ./:/usr/stat_inc/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - proxynet
    labels:
      - traefik.enable=true
      - traefik.http.services.bot_service.loadbalancer.server.port=8000
      - traefik.http.routers.bot_service.entrypoints=http
      - traefik.http.routers.bot_service.rule=PathPrefix("/api/bots")
      - traefik.docker.network=stat_inc_network

  worker:
    build: .
    command: celery -A core.celery.app worker -P threads --loglevel=${LOG_LEVEL} --logfile=celery.log
    volumes:
      - ./:/usr/stat_inc/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - bot_service
      - redis
    networks:
      - proxynet

  redis:
    image: redis:6-alpine
    networks:
      - proxynet

  selenium_bots_creation:
    image: selenium/standalone-chrome:101.0
    networks:
      - proxynet

  selenium_boost:
    image: selenium/standalone-chrome:101.0
    networks:
      - proxynet


networks:
  proxynet:
    name: stat_inc_network