version: '3.8'

services:

  bot_service:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./:/usr/stat_inc/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - proxynet

  worker:
    build: .
    command: celery -A core.celery.app worker -P threads --loglevel=info --logfile=celery.log
    volumes:
      - ./:/usr/stat_inc/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - bot_service
      - redis
    networks:
      - proxynet

  redis:
    image: redis:6-alpine
    networks:
      - proxynet

  selenium_bots_creation:
    image: selenium/standalone-chrome:101.0
    ports:
      - "4445:4444"
    networks:
      - proxynet

  selenium_boost:
    image: selenium/standalone-chrome:101.0
    ports:
      - "4444:4444"
    networks:
      - proxynet


networks:
  proxynet:
    name: custom_network