version: '3.8'

services:

  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./:/usr/stat_inc/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core.celery.app worker --loglevel=info
    volumes:
      - ./:/usr/stat_inc/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine